"""added reviews table

Revision ID: 46ef05e6be0f
Revises: e9540f12bb49
Create Date: 2025-03-05 17:04:42.208879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46ef05e6be0f'
down_revision: Union[str, None] = 'e9540f12bb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_uid', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'book_uid')
    # ### end Alembic commands ###
