"""added user_uid fk to clubs table and removed club_uid fromusers table

Revision ID: 63f157d63345
Revises: fdb2b008acdc
Create Date: 2025-04-01 10:16:02.532353

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f157d63345'
down_revision: Union[str, None] = 'fdb2b008acdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'clubs', 'users', ['user_uid'], ['uid'])
    op.drop_constraint('users_club_uid_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'club_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('club_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_club_uid_fkey', 'users', 'clubs', ['club_uid'], ['uid'])
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'user_uid')
    # ### end Alembic commands ###
