"""added role field to user table

Revision ID: cefbf9a14a3d
Revises: 121246c54bea
Create Date: 2025-04-01 09:31:50.061771

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cefbf9a14a3d'
down_revision: Union[str, None] = '121246c54bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.VARCHAR(), server_default='user', nullable=True))
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
