"""added club_uid foregin key to users table

Revision ID: fdb2b008acdc
Revises: cefbf9a14a3d
Create Date: 2025-04-01 10:10:27.221767

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb2b008acdc'
down_revision: Union[str, None] = 'cefbf9a14a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('club_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'clubs', ['club_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'club_uid')
    # ### end Alembic commands ###
